source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
project 'SwiftAlpsSecDemo/SwiftAlpsSecDemo.xcodeproj'
inhibit_all_warnings!
use_frameworks!

target :"SwiftAlpsSecDemo" do

  # example should work with head
  pod 'themis', :git => "https://github.com/cossacklabs/themis.git"

	target "SwiftAlpsSecDemoTests" do
	    inherit! :search_paths
	end
end